puestos/config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  resources :comidas
  #resources :calificas
  devise_for :users do
  	get "perfil"
  end
  root 'home#index'
 # resources :puestos
  resources :puestos do 
  	resources :calificas
  end
  resources :principal

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

puestos/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

puestos/app/models/califica.rb
class Califica < ApplicationRecord
	validates :user_id, uniqueness: { scope: :puesto_id, message: "Ya has hecho un comentario" }

  	belongs_to :user
  	belongs_to :puesto
end

puestos/app/models/comida.rb
class Comida < ApplicationRecord
  belongs_to :puesto
end

puestos/app/models/informacion.rb
class Informacion < ApplicationRecord
end

puestos/app/models/puesto.rb
class Puesto < ApplicationRecord
	has_many :calificas
	has_many :users#, :through => :calificas 
end

puestos/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_format_of :email, with: /\@ciencias\.unam.mx/, message: "Tu correo debe ser @ciencias.unam.mx"
  #has_many :calificas 
  has_many :puestos, dependent: :destroy#, :through => :calificas

end

puestos/app/models/usuario.rb
class Usuario < ApplicationRecord
end

puestos/app/controllers/cuenta_controller.rb
class CuentaController < ApplicationController
  def verCuenta
  end
end

puestos/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

puestos/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = current_user
  	@user.calificas.build
  	@user.puestos.build
  end
end

puestos/app/helpers/application_helper.rb
module ApplicationHelper
end

puestos/app/helpers/calificas_helper.rb
module CalificasHelper
end

puestos/app/helpers/comidas_helper.rb
module ComidasHelper
end

puestos/app/helpers/cuenta_helper.rb
module CuentaHelper
end

puestos/app/helpers/home_helper.rb
module HomeHelper
end

puestos/app/helpers/principal_helper.rb
module PrincipalHelper
end

puestos/app/helpers/puesto_helper.rb
module PuestoHelper
end

puestos/app/helpers/puestos_helper.rb
module PuestosHelper
end

puestos/app/helpers/users_helper.rb
module UsersHelper
end

puestos/app/helpers/usuario_helper.rb
module UsuarioHelper
end

puestos/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Puestos</title>
  <script src="//maps.google.com/maps/api/js?key=AIzaSyBAh0iPRXyxLlBEc2z93ddYtiD5f5TjdCk" type="text/javascript"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js" type="text/javascript"></script>
  <script src="//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" type="text/javascript"></script>
  
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel='shortcut icon' type='image/x-icon' href='/favicon.ico' />

</head>

<body>
  <header>

   <nav>
    <div class="nav-wrapper">
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li>
          <%= link_to "Inicio", root_path%>   
        </li>
        <%if user_signed_in?%>
        <%if current_user.isAdmin?%>
        <li>
          <%= link_to "Administrar cuentas", users_index_path%>   
        </li>
        <%end%>
        <li>
          <%= link_to "Ver cuenta", principal_index_path%>   
        </li>
        <li>
         <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete%>
       </li>
       <%else%>
       <li>
        <%= link_to "Iniciar sesion", new_user_session_path%> 
      </li>
      <li>
        <%= link_to "Registrate", new_user_registration_path%> 
      </li>
      <%end%>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li class="navi">
        <i class="material-icons icon-nav">home</i><%= link_to "Inicio", root_path%>   
      </li><br>
      <%if user_signed_in?%>
      <%if current_user.isAdmin?%>
      <li class="navi">
        <i class="material-icons icon-nav">supervisor_account</i><%= link_to "Administrar cuentas", users_index_path%>   
      </li><br>
      <%end%>
      <li class="navi">
        <i class="material-icons icon-nav">account_circle</i><%= link_to "Ver cuenta", principal_index_path%>   
      </li><br>
      <li class="navi">
        <i class="material-icons icon-nav">exit_to_app</i><%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete%>
      </li><br>
      <%else%>
      <li class="navi">
        <i class="material-icons icon-nav">lock</i><%= link_to "Iniciar sesion", new_user_session_path%> 
      </li><br>
      <li class="navi">
        <i class="material-icons icon-nav">home</i><%= link_to "Registrate", new_user_registration_path%> 
      </li>

      <%end%>
    </ul>
  </div>
</nav>
</header>
<main>
  <%= yield %>
</main>
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s6">
        <h5 class="white-text">Desarrollado por <h5 class="interphy">Interphy</h5></h5>
        <p class="grey-text text-lighten-4">En el equipo de desarrollo de Interphy somos personas especializadas en el desarrollo de Software además de ser amantes de la tecnología.</p>
      </div>
      <div class="col l4 s6">
        <h5 class="white-text">Equipo</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Aguilar Valenzuela Zaide Esther</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Hernández Olvera Mauricio Eduardo</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Jaime Flores Jessica</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Pérez Márquez José Alejandro</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Salazar González Edwin Max </a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2017 Interphy
    </div>
  </footer>
</body>
<script type="text/javascript">
  $(".button-collapse").sideNav();
</script>
</html>