puestos/config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  resources :comidas
  #resources :calificas
  devise_for :users do
  	get "perfil"
  end
  root 'home#index'
 # resources :puestos
  resources :puestos do 
  	resources :calificas
  end
  resources :principal

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

puestos/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

puestos/app/models/califica.rb
class Califica < ApplicationRecord
	validates :user_id, uniqueness: { scope: :puesto_id, message: "Ya has hecho un comentario" }

  	belongs_to :user
  	belongs_to :puesto
end

puestos/app/models/comida.rb
class Comida < ApplicationRecord
  belongs_to :puesto
end

puestos/app/models/informacion.rb
class Informacion < ApplicationRecord
end

puestos/app/models/puesto.rb
class Puesto < ApplicationRecord
	has_many :calificas
	has_many :users#, :through => :calificas 
end

puestos/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_format_of :email, with: /\@ciencias\.unam.mx/, message: "Tu correo debe ser @ciencias.unam.mx"
  #has_many :calificas 
  has_many :puestos, dependent: :destroy#, :through => :calificas

end

puestos/app/models/usuario.rb
class Usuario < ApplicationRecord
end

puestos/app/controllers/calificas_controller.rb
class CalificasController < ApplicationController
  before_action :set_califica, only: [:show, :edit, :update]
  before_action :check_califica, only: [:new, :create]

  # GET /calificas
  # GET /calificas.json
  def index
    @calificas = Califica.all
  end

  # GET /calificas/1
  # GET /calificas/1.json
  def show
  end

  # GET /calificas/new
  def new
    @califica = Califica.new
  end

  # GET /calificas/1/edit
  def edit
    @puesto = Puesto.find(params[:puesto_id])
    @califica = @puesto.calificas.find(params[:id])
  end

  # POST /calificas
  # POST /calificas.json
  def create

    @puesto = Puesto.find(params[:puesto_id])
    parametros = califica_params
    parametros[:user_id] = current_user.id
    #califica_params[:user_id] = current_user.id
    @califica = @puesto.calificas.create(parametros) #@puesto.calificas.create({:user_id => 1, :puesto_id => 1, :comentario => "bien", :estrellas => 2}) #Califica.new(califica_params)

    redirect_to puesto_path(@puesto)

    if false
      respond_to do |format|
        if @califica.save
          format.html { redirect_to @califica, notice: 'Califica was successfully created.' }
          format.json { render :show, status: :created, location: @califica }
        else
          format.html { render :new }
          format.json { render json: @califica.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /calificas/1
  # PATCH/PUT /calificas/1.json
  def update
    respond_to do |format|
      if @califica.update(califica_params)
        format.html { redirect_to @califica, notice: 'Califica was successfully updated.' }
        format.json { render :show, status: :ok, location: @califica }
      else
        format.html { render :edit }
        format.json { render json: @califica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calificas/1
  # DELETE /calificas/1.json
  def destroy
    @puesto = Puesto.find(params[:puesto_id])
    @califica = @puesto.calificas.find(params[:id])
    @califica.destroy

    redirect_to puesto_path(@puesto)
    if false
    respond_to do |format|
      format.html { redirect_to calificas_url, notice: 'Califica was successfully destroyed.' }
      format.json { head :no_content }
    end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_califica
      @califica = Califica.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def califica_params
      #@user_id = current_user.id
      params.require(:califica).permit(:user_id,:comentario, :estrellas)
    end

    def check_califica
      #@puesto = Puesto.find(params[:puesto_id])
      #if @puesto.calificas.find(params[:id])
        #flash[:notice] = "Ya has comentado antes, puedes editarlo si quieres"
        #redirect_to puesto_path(@puesto)
      #end
    end
end

puestos/app/controllers/comidas_controller.rb
class ComidasController < ApplicationController
  before_action :set_comida, only: [:show, :edit, :update, :destroy]

  # GET /comidas
  # GET /comidas.json
  def index
    @comidas = Comida.all
  end

  # GET /comidas/1
  # GET /comidas/1.json
  def show
  end

  # GET /comidas/new
  def new
    @comida = Comida.new
  end

  # GET /comidas/1/edit
  def edit
  end

  # POST /comidas
  # POST /comidas.json
  def create
    @comida = Comida.new(comida_params)

    respond_to do |format|
      if @comida.save
        format.html { redirect_to @comida, notice: 'Comida was successfully created.' }
        format.json { render :show, status: :created, location: @comida }
      else
        format.html { render :new }
        format.json { render json: @comida.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comidas/1
  # PATCH/PUT /comidas/1.json
  def update
    respond_to do |format|
      if @comida.update(comida_params)
        format.html { redirect_to @comida, notice: 'Comida was successfully updated.' }
        format.json { render :show, status: :ok, location: @comida }
      else
        format.html { render :edit }
        format.json { render json: @comida.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comidas/1
  # DELETE /comidas/1.json
  def destroy
    @comida.destroy
    respond_to do |format|
      format.html { redirect_to comidas_url, notice: 'Comida was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comida
      @comida = Comida.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comida_params
      params.require(:comida).permit(:tipo, :costo, :puesto_id)
    end
end

puestos/app/controllers/cuenta_controller.rb
class CuentaController < ApplicationController
  def verCuenta
  end
end

puestos/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

puestos/app/controllers/puesto_controller.rb
class PuestoController < ApplicationController
  def crearPuesto
  end

  def verPuesto
    #id = params['id']
    #p = Puesto.find(id)
    if p.nil?
      @puesto =  Puesto.find(params[:idPuesto])
    #@puesto = p
    else
    @puesto = Puesto.new
    end
  end

  def crearComentario
  end

  def verComentarios
  end

  def create
    nombre = params['nombre']
    numPuesto = params['numPuesto']
    imagen = params['imagen']
    p = Puesto.new
    p.nombre = nombre
    p.numPuestoUNAM = numPuesto
    p.imagen = imagen
    if p.save
        flash[:mensaje] = 'chido'
    else
        flash[:mensaje] = 'chale'
    end
  end
end

puestos/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = current_user
  	@user.calificas.build
  	@user.puestos.build
  end
end

puestos/app/helpers/application_helper.rb
module ApplicationHelper
end

puestos/app/helpers/calificas_helper.rb
module CalificasHelper
end

puestos/app/helpers/comidas_helper.rb
module ComidasHelper
end

puestos/app/helpers/cuenta_helper.rb
module CuentaHelper
end

puestos/app/helpers/home_helper.rb
module HomeHelper
end

puestos/app/helpers/principal_helper.rb
module PrincipalHelper
end

puestos/app/helpers/puesto_helper.rb
module PuestoHelper
end

puestos/app/helpers/puestos_helper.rb
module PuestosHelper
end

puestos/app/helpers/users_helper.rb
module UsersHelper
end

puestos/app/helpers/usuario_helper.rb
module UsuarioHelper
end

puestos/app/views/calificas/_form.html.erb
<%if false%>
<%= form_for(califica) do |f| %>
  <% if califica.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(califica.errors.count, "error") %> prohibited this califica from being saved:</h2>

      <ul>
      <% califica.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :puesto_id %>
    <%= f.text_field :puesto_id %>
  </div>

  <div class="field">
    <%= f.label :comentario %>
    <%= f.text_area :comentario %>
  </div>

  <div class="field">
    <%= f.label :estrellas %>
    <%= f.number_field :estrellas %>
  </div>

  <div class="actions">
    <%= f.submit "Comentar" %>
  </div>
<% end %>
<% end %>
<h6>Añade un comentario</h6>
  
  <%= form_for([@puesto, @puesto.calificas.build]) do |f| %>
  
    <p>
      <%= f.label :comentario %><br>
      <%= f.text_area :comentario %>
    </p>
    <p>
      <%= f.label :estrellas%>
      <%= f.number_field :estrellas%>  
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>

puestos/app/views/calificas/edit.html.erb
<div class="container">
	<h1>Editando comentario</h1>

	<%= render 'form', califica: @califica %>

	<%= link_to 'Show', @califica %> |
	<%= link_to 'Back', calificas_path %>
</div>

puestos/app/views/calificas/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Calificas</h1>

  <table>
    <thead>
      <tr>
        <th>User</th>
        <th>Puesto</th>
        <th>Comentario</th>
        <th>Estrellas</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @calificas.each do |califica| %>
        <tr>
          <td><%= califica.user %></td>
          <td><%= califica.puesto %></td>
          <td><%= califica.comentario %></td>
          <td><%= califica.estrellas %></td>
          <td><%= link_to 'Show', califica %></td>
          <td><%= link_to 'Edit', edit_califica_path(califica) %></td>
          <td><%= link_to 'Destroy', califica, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Califica', new_califica_path %>
</div>

puestos/app/views/calificas/new.html.erb
<div class="container">
	<h1>Crear comentario</h1>

	<%= render 'form', califica: @califica %>

	<%= link_to 'Regresar', puestos_path %>
</div>

puestos/app/views/calificas/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>User:</strong>
	  <%= @califica.user.email %>
	</p>

	<p>
	  <strong>Puesto:</strong>
	  <%= @califica.puesto.nombre %>
	</p>

	<p>
	  <strong>Comentario:</strong>
	  <%= @califica.comentario %>
	</p>

	<p>
	  <strong>Estrellas:</strong>
	  <%= @califica.estrellas %>
	</p>

	<%= link_to 'Edit', edit_califica_path(@califica) %> |
	<%= link_to 'Back', puestos_path %>
</div>