puestos/config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  resources :comidas
  #resources :calificas
  devise_for :users do
  	get "perfil"
  end
  root 'home#index'
 # resources :puestos
  resources :puestos do 
  	resources :calificas
  end
  resources :principal

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

puestos/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

puestos/app/models/califica.rb
class Califica < ApplicationRecord
	validates :user_id, uniqueness: { scope: :puesto_id, message: "Ya has hecho un comentario" }

  	belongs_to :user
  	belongs_to :puesto
end

puestos/app/models/comida.rb
class Comida < ApplicationRecord
  belongs_to :puesto
end

puestos/app/models/informacion.rb
class Informacion < ApplicationRecord
end

puestos/app/models/puesto.rb
class Puesto < ApplicationRecord
	has_many :calificas
	has_many :users#, :through => :calificas 
end

puestos/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_format_of :email, with: /\@ciencias\.unam.mx/, message: "Tu correo debe ser @ciencias.unam.mx"
  #has_many :calificas 
  has_many :puestos, dependent: :destroy#, :through => :calificas

end

puestos/app/models/usuario.rb
class Usuario < ApplicationRecord
end

puestos/app/controllers/comidas_controller.rb
class ComidasController < ApplicationController
  before_action :set_comida, only: [:show, :edit, :update, :destroy]

  # GET /comidas
  # GET /comidas.json
  def index
    @comidas = Comida.all
  end

  # GET /comidas/1
  # GET /comidas/1.json
  def show
  end

  # GET /comidas/new
  def new
    @comida = Comida.new
  end

  # GET /comidas/1/edit
  def edit
  end

  # POST /comidas
  # POST /comidas.json
  def create
    @comida = Comida.new(comida_params)

    respond_to do |format|
      if @comida.save
        format.html { redirect_to @comida, notice: 'Comida was successfully created.' }
        format.json { render :show, status: :created, location: @comida }
      else
        format.html { render :new }
        format.json { render json: @comida.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comidas/1
  # PATCH/PUT /comidas/1.json
  def update
    respond_to do |format|
      if @comida.update(comida_params)
        format.html { redirect_to @comida, notice: 'Comida was successfully updated.' }
        format.json { render :show, status: :ok, location: @comida }
      else
        format.html { render :edit }
        format.json { render json: @comida.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comidas/1
  # DELETE /comidas/1.json
  def destroy
    @comida.destroy
    respond_to do |format|
      format.html { redirect_to comidas_url, notice: 'Comida was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comida
      @comida = Comida.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comida_params
      params.require(:comida).permit(:tipo, :costo, :puesto_id)
    end
end

puestos/app/controllers/cuenta_controller.rb
class CuentaController < ApplicationController
  def verCuenta
  end
end

puestos/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

puestos/app/controllers/puesto_controller.rb
class PuestoController < ApplicationController
  def crearPuesto
  end

  def verPuesto
    #id = params['id']
    #p = Puesto.find(id)
    if p.nil?
      @puesto =  Puesto.find(params[:idPuesto])
    #@puesto = p
    else
    @puesto = Puesto.new
    end
  end

  def crearComentario
  end

  def verComentarios
  end

  def create
    nombre = params['nombre']
    numPuesto = params['numPuesto']
    imagen = params['imagen']
    p = Puesto.new
    p.nombre = nombre
    p.numPuestoUNAM = numPuesto
    p.imagen = imagen
    if p.save
        flash[:mensaje] = 'chido'
    else
        flash[:mensaje] = 'chale'
    end
  end
end

puestos/app/controllers/puestos_controller.rb
class PuestosController < ApplicationController
  before_action :set_puesto, only: [:show, :edit, :update, :destroy]

  # GET /puestos
  # GET /puestos.json
  def index
    @puestos = Puesto.all
    @hash = Gmaps4rails.build_markers(@puestos) do |puesto, marker|
      marker.lat puesto.lat
      marker.lng puesto.lng
      marker.infowindow puesto.nombre
    end
  end

  # GET /puestos/1
  # GET /puestos/1.json
  def show
    @califica = Puesto.find(params[:id]).calificas
  end

  # GET /puestos/new
  def new
    @puesto = Puesto.new
    @puestos = Puesto.all
    @hash = Gmaps4rails.build_markers(@puestos) do |puesto, marker|
      marker.lat puesto.lat
      marker.lng puesto.lng
      marker.infowindow puesto.nombre
    @puesto.calificas.build
    #@puesto.users.build
    end
  end

  # GET /puestos/1/edit
  def edit
    @puestoe = Puesto.find(params[:id])
    @puestos = Puesto.all
    @hash = Gmaps4rails.build_markers(@puestos) do |puesto, marker|
      marker.lat puesto.lat
      marker.lng puesto.lng
      marker.infowindow puesto.nombre
    end
  end

  # POST /puestos
  # POST /puestos.json
  def create
    @puesto = Puesto.new(puesto_params)

    respond_to do |format|
      if @puesto.save
        format.html { redirect_to @puesto, notice: 'Puesto was successfully created.' }
        format.json { render :show, status: :created, location: @puesto }
      else
        format.html { render :new }
        format.json { render json: @puesto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /puestos/1
  # PATCH/PUT /puestos/1.json
  def update
    respond_to do |format|
      if @puesto.update(puesto_params)
        format.html { redirect_to @puesto, notice: 'Puesto was successfully updated.' }
        format.json { render :show, status: :ok, location: @puesto }
      else
        format.html { render :edit }
        format.json { render json: @puesto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puestos/1
  # DELETE /puestos/1.json
  def destroy
    @puesto.destroy
    respond_to do |format|
      format.html { redirect_to puestos_url, notice: 'Puesto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_puesto
      @puesto = Puesto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def puesto_params
      params.require(:puesto).permit(:nombre, :numPuestoUNAM, :imagen, :horario, :info_general, :coordenadas, :lat, :lng)
    end
end

puestos/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = current_user
  	@user.calificas.build
  	@user.puestos.build
  end
end

puestos/app/helpers/application_helper.rb
module ApplicationHelper
end

puestos/app/helpers/calificas_helper.rb
module CalificasHelper
end

puestos/app/helpers/comidas_helper.rb
module ComidasHelper
end

puestos/app/helpers/cuenta_helper.rb
module CuentaHelper
end

puestos/app/helpers/home_helper.rb
module HomeHelper
end

puestos/app/helpers/principal_helper.rb
module PrincipalHelper
end

puestos/app/helpers/puesto_helper.rb
module PuestoHelper
end

puestos/app/helpers/puestos_helper.rb
module PuestosHelper
end

puestos/app/helpers/users_helper.rb
module UsersHelper
end

puestos/app/helpers/usuario_helper.rb
module UsuarioHelper
end

puestos/app/views/comidas/_form.html.erb
<%= form_for(comida) do |f| %>
  <% if comida.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comida.errors.count, "error") %> prohibited this comida from being saved:</h2>

      <ul>
      <% comida.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %>
    <%= f.text_area :tipo %>
  </div>

  <div class="field">
    <%= f.label :costo %>
    <%= f.text_field :costo %>
  </div>

  <div class="field">
    <%= f.label :puesto_id %>
    <%= f.text_field :puesto_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

puestos/app/views/comidas/edit.html.erb
<h1>Editing Comida</h1>

<%= render 'form', comida: @comida %>

<%= link_to 'Show', @comida %> |
<%= link_to 'Back', comidas_path %>

puestos/app/views/comidas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comidas</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Costo</th>
      <th>Puesto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comidas.each do |comida| %>
      <tr>
        <td><%= comida.tipo %></td>
        <td><%= comida.costo %></td>
        <td><%= comida.puesto %></td>
        <td><%= link_to 'Show', comida %></td>
        <td><%= link_to 'Edit', edit_comida_path(comida) %></td>
        <td><%= link_to 'Destroy', comida, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', puestos_path %>

puestos/app/views/comidas/new.html.erb
<h1>New Comida</h1>

<%= render 'form', comida: @comida %>

<p><%=link_to"Regresar",puestos_path%></p>

puestos/app/views/comidas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @comida.tipo %>
</p>

<p>
  <strong>Costo:</strong>
  <%= @comida.costo %>
</p>

<p>
  <strong>Puesto:</strong>
  <%= @comida.puesto %>
</p>

<%= link_to 'Edit', edit_comida_path(@comida) %> |
<%= link_to 'Back', comidas_path %>

puestos/app/views/users/index.html.erb
<div class="container">
	<h1>Cuentas de usuarios</h1>
	<%if user_signed_in? && current_user.isAdmin?%>
	<% @users = User.all%>
	<% @users.each do |u|%>
	<table class="highlight">
		<thead>
			<tr>
				<th>Correo</th>
				<th></th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			<tr>
				<td><%= u.email%></td>
				<%end%>
				<td><i class="material-icons">delete</i></td>
				<td><i class="material-icons">mode_edit</i></td>
			</tr>
		</tbody>
	</table>
	<%else%>
	<%= current_user.email%><br/>
	<%end%>
</div>

puestos/app/views/users/perfil.html.erb
<div class="container">
  <div class ="hola"style='width: 100%;'> 
      <div id="multi_markers" class = "map"></div>
      <div class = "puestos">
          <h1>Puestos</h1>
          <div class="row enlistaPuestos style-10">
            <% @puestos.each do |puesto| %>
            <div class="col m12">
              <div class="card-panel" style="width : 410px ">
                <span class="white-text">
                    <%= puesto.nombre %> 
                </span>
                <div class="card-action">
                    <%= link_to 'visibility', puesto, :class=>"medium material-icons visibility"%>
                </div>
            </div>
        </div>
        <%end%>
    </div>
  </div>
  </div>
  <%if user_signed_in? && current_user.isAdmin?%>
  <div class="fixed-action-btn">
    <%= link_to "add".html_safe, new_puesto_path, :class=>"btn-floating btn-large large material-icons add" %>
  </div>
  <%end%>
  <br>
  <%= link_to "navigate_before".html_safe, root_path, :class=>"medium material-icons" %>
</div>

  <!--
  <h1>Puestos</h1>
  <table>
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Numpuestounam</th>
        <th>Imagen</th>
        <th>Horario</th>
        <th>Info general</th>
        <th>Coordenadas</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @puestos.each do |puesto| %>
        <tr>
          <td><%= puesto.nombre %></td>
          <td><%= puesto.numPuestoUNAM %></td>
          <td><%= puesto.imagen %></td>
          <td><%= puesto.horario %></td>
          <td><%= puesto.info_general %></td>
          <td><%= puesto.coordenadas %></td>
          <td><%= link_to 'Show', puesto %></td>
          <td><%= link_to 'Edit', edit_puesto_path(puesto) %></td>
          <td><%= link_to 'Destroy', puesto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>

  </tbody>
</table>

<script type="text/javascript" async defer>
        var mapStyle = [
        {
            "featureType": "water",
            "stylers": [
            {
                "color": "#021019"
            }
            ]
        },
        {
            "featureType": "landscape",
            "stylers": [
            {
                "color": "#08304b"
            }
            ]
        },
        {
            "featureType": "poi",
            "elementType": "geometry",
            "stylers": [
            {
                "color": "#0c4152"
            },
            {
                "lightness": 5
            }
            ]
        },
        {
            "featureType": "road.highway",
            "elementType": "geometry.fill",
            "stylers": [
            {
                "color": "#000000"
            }
            ]
        },
        {
            "featureType": "road.highway",
            "elementType": "geometry.stroke",
            "stylers": [
            {
                "color": "#0b434f"
            },
            {
                "lightness": 25
            }
            ]
        },
        {
            "featureType": "road.arterial",
            "elementType": "geometry.fill",
            "stylers": [
            {
                "color": "#000000"
            }
            ]
        },
        {
            "featureType": "road.arterial",
            "elementType": "geometry.stroke",
            "stylers": [
            {
                "color": "#0b3d51"
            },
            {
                "lightness": 16
            }
            ]
        },
        {
            "featureType": "road.local",
            "elementType": "geometry",
            "stylers": [
            {
                "color": "#000000"
            }
            ]
        },
        {
            "elementType": "labels.text.fill",
            "stylers": [
            {
                "color": "#ffffff"
            }
            ]
        },
        {
            "elementType": "labels.text.stroke",
            "stylers": [
            {
                "color": "#000000"
            },
            {
                "lightness": 13
            }
            ]
        },
        {
            "featureType": "transit",
            "stylers": [
            {
                "color": "#146474"
            }
            ]
        },
        {
            "featureType": "administrative",
            "elementType": "geometry.fill",
            "stylers": [
            {
                "color": "#000000"
            }
            ]
        },
        {
            "featureType": "administrative",
            "elementType": "geometry.stroke",
            "stylers": [
            {
                "color": "#144b53"
            },
            {
                "lightness": 14
            },
            {
                "weight": 1.4
            }
            ]
        }
        ];

handler = Gmaps.build('Google');
handler.buildMap({ provider: {styles:    mapStyle}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(
    [
      {
        "lat": 19.323842,
        "lng": -99.178965,
      }
    ]
  ,{ draggable: true}
  );
  handler.addMarkers([{
        "lat": 19.323842,
        "lng": -99.178965,
  }]);
  handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();

  // Move existing marker
  google.maps.event.addListener(markers[0].serviceObject, 'dragend', function() {
    updateFormLocation(this.getPosition());
  });
});

// Update form attributes with given coordinates
function updateFormLocation(latLng) {
  $('#latitude').val(latLng.lat());
  $('#longitude').val(latLng.lng());
  console.log("coordenadas:" + latLng.lat() + latLng.lng());
}
    </script>

<br>-->